kafka:
  enabled: false
config:
  port: 80
  logLevel: info
  wsPingIntervalMs: 500
  kafkaLogLevel: 'nothing'
  kafkaBrokers: 'kafka:9092'
  kafkaNotificationEventsTopic: event-notifications
  notificationsReplicationFactor: 1
  notificationsPartitions: 5
image:
  repository: ghcr.io/digicatapult/wasp-ws-event-service
  pullPolicy: IfNotPresent
  tag: 'v0.0.7'
  pullSecrets: ['ghcr-digicatapult']
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  paths:
    - /thing/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/event
